### ISSUE TITLE
[not a issue] How can I fork this repo and pr?

### ISSUE THREAD

**Issue by TylerTemp** [bazaar-projects/docopt#9]
Hi,

I'd like to fork this repo and pr but, when I fork it, I can only get a fork of the original `docopt`.

And looks like it's impossible to [fork a fork](https://stackoverflow.com/questions/6675994/is-it-possible-to-fork-a-fork-in-github):

> I contacted GitHub support about this 'issue' and they confirmed this is not possible. Also, it is very unlikely that such a feature will be implemented in the future.

**Comment by itdaniher** [comment]
I'm gonna break the fork - rename this, make a fresh repo, and push this. I'll do it tomorrow.

Cheers!

**Comment by itdaniher** [comment]
@TylerTemp Done! You should be able to fork https://github.com/bazaar-projects/docopt-ng/ and open PRs. Thanks for your interest!
